"use client";
import { useState, type FormEvent } from "react";
import { AlertCircle, CheckCircle2, MessageSquareWarning } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { buildBugReportRequestBody, getBugReportModeNote, isBugReportSubmitDisabled, resolveBugReportFeedback, type BugReportFeedback } from "./reportBugButton.logic";
export function ReportBugButton({ meetingId }: { meetingId?: string }) {
  const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [isSubmitting, setIsSubmitting] = useState(false); const [feedback, setFeedback] = useState<BugReportFeedback | null>(null); const note = getBugReportModeNote(meetingId);
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (isBugReportSubmitDisabled(message, isSubmitting)) return; setIsSubmitting(true); setFeedback(null); try { const response = await fetch("/api/bug-report", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(buildBugReportRequestBody(message, meetingId)) }); const body = await response.json().catch(() => ({})); setFeedback(resolveBugReportFeedback(response.ok, body?.error)); if (response.ok) setMessage(""); } catch { setFeedback(resolveBugReportFeedback(false)); } finally { setIsSubmitting(false); } }
  if (!open) return <Button type="button" variant="outline" size="sm" className="gap-1.5" onClick={() => setOpen(true)}><MessageSquareWarning className="h-3.5 w-3.5" />Reportar un problema</Button>;
  return <form onSubmit={handleSubmit} className="space-y-2"><textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Contanos qué pasó..." rows={3} maxLength={2000} disabled={isSubmitting} aria-label="Mensaje del reporte" className="w-full rounded-[var(--radius)] px-3 py-2 text-sm" />{note && <p className="text-xs text-[var(--muted-foreground)]">{note}</p>}{feedback && <div role="status" className="flex items-center gap-2 text-xs">{feedback.type === "success" ? <CheckCircle2 className="h-3.5 w-3.5" /> : <AlertCircle className="h-3.5 w-3.5" />}{feedback.text}</div>}<div className="flex items-center gap-2"><Button type="submit" variant="primary" size="sm" disabled={isBugReportSubmitDisabled(message, isSubmitting)}>{isSubmitting ? "Enviando..." : "Enviar reporte"}</Button><Button type="button" variant="ghost" size="sm" onClick={() => { setOpen(false); setFeedback(null); }}>Cancelar</Button></div></form>;
}
